# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"\"\n\x11\x43reateTodoRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1b\n\rTodoIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"4\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"%\n\x08TodoList\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo\"\x07\n\x05\x45mpty2\xcd\x01\n\x0bTodoService\x12\x31\n\nCreateTodo\x12\x17.todo.CreateTodoRequest\x1a\n.todo.Todo\x12(\n\tListTodos\x12\x0b.todo.Empty\x1a\x0e.todo.TodoList\x12\x31\n\x0eToggleComplete\x12\x13.todo.TodoIdRequest\x1a\n.todo.Todo\x12.\n\nDeleteTodo\x12\x13.todo.TodoIdRequest\x1a\x0b.todo.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATETODOREQUEST']._serialized_start=20
  _globals['_CREATETODOREQUEST']._serialized_end=54
  _globals['_TODOIDREQUEST']._serialized_start=56
  _globals['_TODOIDREQUEST']._serialized_end=83
  _globals['_TODO']._serialized_start=85
  _globals['_TODO']._serialized_end=137
  _globals['_TODOLIST']._serialized_start=139
  _globals['_TODOLIST']._serialized_end=176
  _globals['_EMPTY']._serialized_start=178
  _globals['_EMPTY']._serialized_end=185
  _globals['_TODOSERVICE']._serialized_start=188
  _globals['_TODOSERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
